package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"strings"
	"text/template"
)

const (
	apiDir     = "api"
	outputFile = "api/api_execute_all_gen.go"
)

type RequestInfo struct {
	RequestStruct  string
	ModelStruct    string
	ResultType     string
	IsLog          bool
	ResultsField   string
	DefaultLimit   int
}

var executeAllTemplate = `// Code generated by gen-execute-all; DO NOT EDIT.

package api

import (
	"net/http"
)

{{ range . }}
// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *{{ .ModelStruct }}: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r {{ .RequestStruct }}) ExecuteAll() (res *{{ .ModelStruct }}, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "{{ .RequestStruct }}.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []{{ .ResultType }}
	offset := int32(0)
	limit := int32({{ .DefaultLimit }})
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *{{ .ModelStruct }}
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.{{ .ResultsField }} != nil {
			allResults = append(allResults, resp.{{ .ResultsField }}...)
			if int32(len(resp.{{ .ResultsField }})) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &{{ .ModelStruct }}{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		{{ .ResultsField }}: allResults,
	}
	return res, lastResp, nil
}

{{ end }}
`

func main() {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, apiDir, nil, 0)
	if err != nil {
		log.Fatal(err)
	}

	var requests []RequestInfo
	pkg, ok := pkgs["api"]
	if !ok {
		log.Fatalf("package api not found")
	}

	// 1. Find all eligible Request structs
	for _, file := range pkg.Files {
		ast.Inspect(file, func(n ast.Node) bool {
			ts, ok := n.(*ast.TypeSpec)
			if !ok {
				return true
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				return true
			}

			if !strings.HasPrefix(ts.Name.Name, "Api") || !strings.HasSuffix(ts.Name.Name, "Request") {
				return true
			}

			hasOffset := false
			hasLimit := false
			for _, field := range st.Fields.List {
				for _, name := range field.Names {
					if name.Name == "offset" {
						hasOffset = true
					}
					if name.Name == "limit" {
						hasLimit = true
					}
				}
			}

			if hasOffset && hasLimit {
				// Find Execute method to determine return type
				modelStruct, resultType, resultsField := findExecuteInfo(pkg, ts.Name.Name)
				if modelStruct != "" {
					req := RequestInfo{
						RequestStruct: ts.Name.Name,
						ModelStruct:   modelStruct,
						ResultType:    resultType,
						IsLog:         strings.Contains(ts.Name.Name, "Log"),
						ResultsField:  resultsField,
						DefaultLimit:  10000,
					}
					if req.IsLog {
						req.DefaultLimit = 100
					}
					requests = append(requests, req)
				}
			}
			return true
		})
	}

	if len(requests) == 0 {
		fmt.Println("No paginated requests found.")
		return
	}

	tmpl, err := template.New("executeAll").Parse(executeAllTemplate)
	if err != nil {
		log.Fatal(err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, requests); err != nil {
		log.Fatal(err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("failed to format generated code: %v\n%s", err, buf.String())
	}

	if err := os.WriteFile(outputFile, formatted, 0644); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Generated %d ExecuteAll methods in %s\n", len(requests), outputFile)
}

func findExecuteInfo(pkg *ast.Package, requestStruct string) (string, string, string) {
	var modelStruct string
	for _, file := range pkg.Files {
		ast.Inspect(file, func(n ast.Node) bool {
			fd, ok := n.(*ast.FuncDecl)
			if !ok {
				return true
			}
			if fd.Recv == nil || len(fd.Recv.List) == 0 {
				return true
			}

			// Check receiver type
			recvType := ""
			switch t := fd.Recv.List[0].Type.(type) {
			case *ast.Ident:
				recvType = t.Name
			case *ast.StarExpr:
				if ident, ok := t.X.(*ast.Ident); ok {
					recvType = ident.Name
				}
			}

			if recvType != requestStruct || fd.Name.Name != "Execute" {
				return true
			}

			// Found Execute method, check returns
			if fd.Type.Results != nil && len(fd.Type.Results.List) > 0 {
				// First return is *ModelStruct
				if se, ok := fd.Type.Results.List[0].Type.(*ast.StarExpr); ok {
					if ident, ok := se.X.(*ast.Ident); ok {
						modelStruct = ident.Name
					}
				}
			}
			return true
		})
		if modelStruct != "" {
			break
		}
	}

	if modelStruct == "" {
		return "", "", ""
	}

	// Now find the Results field in modelStruct
	var resultType string
	var resultsField string
	for _, file := range pkg.Files {
		ast.Inspect(file, func(n ast.Node) bool {
			ts, ok := n.(*ast.TypeSpec)
			if !ok {
				return true
			}
			if ts.Name.Name != modelStruct {
				return true
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				return true
			}
			for _, field := range st.Fields.List {
				fieldName := ""
				if len(field.Names) > 0 {
					fieldName = field.Names[0].Name
				}
				if fieldName == "Results" {
					if at, ok := field.Type.(*ast.ArrayType); ok {
						if ident, ok := at.Elt.(*ast.Ident); ok {
							resultType = ident.Name
							resultsField = "Results"
						}
					}
				}
			}
			return true
		})
		if resultType != "" {
			break
		}
	}

	return modelStruct, resultType, resultsField
}
