// Code generated by gen-execute-all; DO NOT EDIT.

package api

import (
	"net/http"

	"go.opentelemetry.io/otel/codes"
)

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetCommonConfigs: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetCommonConfigListRequest) ExecuteAll() (res *GetCommonConfigs, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetCommonConfigListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []CommonConfig
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetCommonConfigs
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetCommonConfigs{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetLbDomains: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetLbDomainListRequest) ExecuteAll() (res *GetLbDomains, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetLbDomainListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []LbDomain
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetLbDomains
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetLbDomains{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetZones: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetContractsZoneListRequest) ExecuteAll() (res *GetZones, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetContractsZoneListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []Zone
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetZones
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetZones{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetZones: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetZoneListRequest) ExecuteAll() (res *GetZones, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetZoneListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []Zone
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetZones
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetZones{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetLbDomains: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetContractsLbDomainListRequest) ExecuteAll() (res *GetLbDomains, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetContractsLbDomainListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []LbDomain
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetLbDomains
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetLbDomains{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetContractsLogs: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetContractsLogListRequest) ExecuteAll() (res *GetContractsLogs, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetContractsLogListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []ContractsLog
	offset := int32(0)
	limit := int32(100)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetContractsLogs
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetContractsLogs{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetRecords: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetRecordCurrentsRequest) ExecuteAll() (res *GetRecords, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetRecordCurrentsRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []Record
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetRecords
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetRecords{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetRecordsDiffs: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetRecordDiffsRequest) ExecuteAll() (res *GetRecordsDiffs, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetRecordDiffsRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []GetRecordsDiffsResultsInner
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetRecordsDiffs
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetRecordsDiffs{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetRecords: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetRecordListRequest) ExecuteAll() (res *GetRecords, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetRecordListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []Record
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetRecords
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetRecords{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetLbDomainsLogs: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetLbDomainsLogListRequest) ExecuteAll() (res *GetLbDomainsLogs, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetLbDomainsLogListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []LbDomainsLog
	offset := int32(0)
	limit := int32(100)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetLbDomainsLogs
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetLbDomainsLogs{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetZoneHistories: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetZoneHistoryListRequest) ExecuteAll() (res *GetZoneHistories, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetZoneHistoryListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []ZoneHistory
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetZoneHistories
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetZoneHistories{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetContracts: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetContractListRequest) ExecuteAll() (res *GetContracts, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetContractListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []Contract
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetContracts
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetContracts{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetTsigsCommonConfigs: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetTsigCommonConfigsRequest) ExecuteAll() (res *GetTsigsCommonConfigs, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetTsigCommonConfigsRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []CommonConfig
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetTsigsCommonConfigs
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetTsigsCommonConfigs{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetTsigs: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetTsigListRequest) ExecuteAll() (res *GetTsigs, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetTsigListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []Tsig
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetTsigs
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetTsigs{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetZonesLogs: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetZonesLogListRequest) ExecuteAll() (res *GetZonesLogs, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetZonesLogListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []ZonesLog
	offset := int32(0)
	limit := int32(100)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetZonesLogs
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetZonesLogs{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}

// ExecuteAll は、ページネーションを利用して全件のリストを自動的に取得し、
// 一つのモデルに集約して返します。
//
// 戻り値:
//   - *GetDelegations: 全件の結果を保持するモデル。
//   - *http.Response: 最後に成功（または失敗）した API リクエストの HTTP レスポンス。
//   - error: 途中の API 呼び出しでエラーが発生した場合に返されます。
func (r ApiGetDelegationListRequest) ExecuteAll() (res *GetDelegations, lastResp *http.Response, err error) {
	ctx, span := r.ApiService.client.tracer.Start(r.ctx, "ApiGetDelegationListRequest.ExecuteAll")
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()
	}()
	r.ctx = ctx
	var allResults []Delegation
	offset := int32(0)
	limit := int32(10000)
	for {
		r = r.Offset(offset)
		r = r.Limit(limit)
		var resp *GetDelegations
		var httpResp *http.Response
		resp, httpResp, err = r.Execute()
		if err != nil {
			return nil, httpResp, err
		}
		lastResp = httpResp
		if resp != nil && resp.Results != nil {
			allResults = append(allResults, resp.Results...)
			if int32(len(resp.Results)) < limit {
				break
			}
		} else {
			break
		}
		offset += limit
	}
	res = &GetDelegations{
		RequestId: lastResp.Header.Get("X-Request-Id"),
		Results:   allResults,
	}
	return res, lastResp, nil
}
