{
  "openapi": "3.0.2",
  "info": {
    "title": "DPF-APIリファレンスマニュアル",
    "version": "1.0",
    "contact": {
      "name": "IIJ サポートセンター",
      "url": "https://help.iij.ad.jp/"
    },
    "description": "# 1. はじめに\n\n## 1.1 DPF-APIについて\nIIJ DNSプラットフォームサービスでは、DNSレコードやゾーン情報などを、\\\nお客様が用意したプログラムから自動的に操作するためのAPI機能を提供しています。\\\n以降、IIJ DNSプラットフォームサービスを「DPF」、DPFが提供するAPIを「DPF-API」あるいは単に「API」と表記します。\\\nDPF-APIの利用には、DPFの契約とIIJ IDサービスの契約が必要となります。\n\n本リファレンスマニュアルは[**OpenAPI**](https://www.openapis.org/)に準拠しています。\n\nこのWEBページはopenapi.jsonから自動生成しています。**このWEBページとopenapi.jsonの内容が異なる場合は、openapi.jsonの内容を正とします。**\nopenapi.jsonは、上部のDownloadボタンからダウンロードできます。\n\n## 1.2 サポート範囲\nDPF-APIを呼び出すためのプログラム、及び[...]"
  },
  "servers": [
    {
      "url": "https://api.dns-platform.jp/dpf/v1",
      "description": "API endpoint"
    }
  ],
  "paths": {
    "/common_configs/{CommonConfigId}/cc_primaries": {
      "get": {
        "operationId": "getCcPrimaryList",
        "summary": "プライマリネームサーバ設定の一覧取得",
        "description": "プライマリネームサーバの設定の一覧を取得します。\n",
        "tags": [
          "cc_primaries"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postCcPrimary",
        "summary": "プライマリネームサーバ設定の作成",
        "description": "新しくプライマリネームサーバを作成します。\\\n作成できる最大件数は5件です。\n",
        "tags": [
          "cc_primaries"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/common_configs/{CommonConfigId}/cc_primaries/{CcPrimaryId}": {
      "get": {
        "operationId": "getCcPrimary",
        "summary": "プライマリネームサーバ設定の取得",
        "description": "指定したCcPrimaryIdのプライマリネームサーバを取得します。\n",
        "tags": [
          "cc_primaries"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchCcPrimary",
        "summary": "プライマリネームサーバ設定の更新",
        "description": "指定したCcPrimaryIdのプライマリネームサーバを更新します。\n",
        "tags": [
          "cc_primaries"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteCcPrimary",
        "summary": "プライマリネームサーバ設定の削除",
        "description": "指定したCcPrimaryIdのプライマリネームサーバを削除します。\n",
        "tags": [
          "cc_primaries"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/common_configs/{CommonConfigId}/cc_sec_notified_servers": {
      "get": {
        "operationId": "getCcSecNotifiedServerList",
        "summary": "DNS NOTIFY設定の一覧取得",
        "description": "DNS NOTIFYの設定の一覧を取得します。\n",
        "tags": [
          "cc_sec_notified_servers"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postCcSecNotifiedServer",
        "summary": "DNS NOTIFY設定の作成",
        "description": "新しくDNS NOFITYを作成します。\\\n作成できる最大件数は256件です。\n",
        "tags": [
          "cc_sec_notified_servers"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/common_configs/{CommonConfigId}/cc_sec_notified_servers/{CcSecNotifiedServerId}": {
      "get": {
        "operationId": "getCcSecNotifiedServer",
        "summary": "DNS NOTIFY設定の取得",
        "description": "指定したCcSecNotifiedServerIdのDNS NOTIFYを取得します。\n",
        "tags": [
          "cc_sec_notified_servers"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchCcSecNotifiedServer",
        "summary": "DNS NOTIFY設定の更新",
        "description": "指定したCcSecNotifiedServerIdのDNS NOTIFYを更新します。\n",
        "tags": [
          "cc_sec_notified_servers"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteCcSecNotifiedServer",
        "summary": "DNS NOTIFY設定の削除",
        "description": "指定したCcSecNotifiedServerIdのDNS NOTIFYを削除します。\n",
        "tags": [
          "cc_sec_notified_servers"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/common_configs/{CommonConfigId}/cc_sec_transfer_acls": {
      "get": {
        "operationId": "getCcSecTransferAclList",
        "summary": "ゾーン転送ACLの一覧取得",
        "description": "ゾーン転送ACLの設定の一覧を取得します。\n",
        "tags": [
          "cc_sec_transfer_acls"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postCcSecTransferAcl",
        "summary": "ゾーン転送ACLの作成",
        "description": "新しくゾーン転送ACLを作成します。\\\n作成できる最大件数は10件です。\n",
        "tags": [
          "cc_sec_transfer_acls"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/common_configs/{CommonConfigId}/cc_sec_transfer_acls/{CcSecTransferAclId}": {
      "get": {
        "operationId": "getCcSecTransferAcl",
        "summary": "ゾーン転送ACLの取得",
        "description": "指定したCcSecTransferAclIdのゾーン転送ACLを取得します。\n",
        "tags": [
          "cc_sec_transfer_acls"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchCcSecTransferAcl",
        "summary": "ゾーン転送ACLの更新",
        "description": "指定したCcSecTransferAclIdのゾーン転送ACLを更新します。\n",
        "tags": [
          "cc_sec_transfer_acls"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteCcSecTransferAcl",
        "summary": "ゾーン転送ACLの削除",
        "description": "指定したCcSecTransferAclIdのゾーン転送ACLを削除します。\n",
        "tags": [
          "cc_sec_transfer_acls"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/common_configs/{CommonConfigId}/cc_notice_accounts": {
      "get": {
        "operationId": "getCcNoticeAccountList",
        "summary": "通知先アカウント設定の一覧取得",
        "description": "通知先アカウントの設定の一覧を取得します。\n",
        "tags": [
          "cc_notice_accounts"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postCcNoticeAccount",
        "summary": "通知先アカウント設定の作成",
        "description": "新しく通知先アカウントを作成します。\n",
        "tags": [
          "cc_notice_accounts"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/common_configs/{CommonConfigId}/cc_notice_accounts/{CcNoticeAccountResourceName}": {
      "get": {
        "operationId": "getCcNoticeAccount",
        "summary": "通知先アカウントの取得",
        "description": "指定したCcNoticeAccountResourceNameの通知先アカウント設定を取得します。\n",
        "tags": [
          "cc_notice_accounts"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchCcNoticeAccount",
        "summary": "通知先アカウント設定の更新",
        "description": "指定したCcNoticeAccountResourceNameの通知先アカウント設定を更新します。\\\nアカウントに登録されたメールアドレスや電話番号を削除したい場合は、空文字を指定してください。\n",
        "tags": [
          "cc_notice_accounts"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteCcNoticeAccount",
        "summary": "通知先アカウント設定の削除",
        "description": "指定したCcNoticeAccountResourceNameの通知先アカウント設定を削除します。\n",
        "tags": [
          "cc_notice_accounts"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/common_configs": {
      "get": {
        "operationId": "getCommonConfigList",
        "summary": "共通設定の一覧取得",
        "description": "共通設定の一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "common_configs"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postCommonConfig",
        "summary": "共通設定の作成",
        "description": "新しく共通設定を作成します。\n",
        "tags": [
          "common_configs"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/common_configs/count": {
      "get": {
        "operationId": "getCommonConfigListCount",
        "summary": "共通設定の件数取得",
        "description": "共通設定の件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "common_configs"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/common_configs/default": {
      "patch": {
        "operationId": "patchCommonConfigDefault",
        "summary": "初期適用される共通設定の更新",
        "description": "ゾーンおよびLBドメインを新規追加した場合に、自動で適用される共通設定を切り替えます。\n",
        "tags": [
          "common_configs"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/common_configs/{CommonConfigId}": {
      "get": {
        "operationId": "getCommonConfig",
        "summary": "共通設定の取得",
        "description": "指定したCommonConfigIdの共通設定を取得します。\n",
        "tags": [
          "common_configs"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchCommonConfig",
        "summary": "共通設定の更新",
        "description": "指定したCommonConfigIdの共通設定を更新します。\n",
        "tags": [
          "common_configs"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteCommonConfig",
        "summary": "共通設定の削除",
        "description": "指定したCommonConfigIdの共通設定を削除します。\n",
        "tags": [
          "common_configs"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/common_configs/{CommonConfigId}/copy": {
      "post": {
        "operationId": "postCommonConfigCopy",
        "summary": "共通設定のコピー",
        "description": "指定した共通設定と同じ内容の共通設定を別の共通設定名で作成します。\n",
        "tags": [
          "common_configs"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/common_configs/{CommonConfigId}/managed_dns": {
      "patch": {
        "operationId": "patchCommonConfigManagedDns",
        "summary": "マネージドDNSサーバの状態更新",
        "description": "マネージドDNSサーバをプライマリネームサーバとして有効もしくは無効とするかの切り替えを行えます。\n",
        "tags": [
          "common_configs"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/contract_partners": {
      "get": {
        "operationId": "getContractPartnerList",
        "summary": "DPF連携サービスの一覧取得",
        "description": "DPFが連携しているサービスの一覧を取得します。\n",
        "tags": [
          "contract_partners"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts": {
      "get": {
        "operationId": "getContractList",
        "summary": "DPF契約情報の一覧取得",
        "description": "DPF契約情報の一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "contracts"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/count": {
      "get": {
        "operationId": "getContractListCount",
        "summary": "DPF契約情報の件数取得",
        "description": "DPF契約の件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "contracts"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}": {
      "get": {
        "operationId": "getContract",
        "summary": "DPF契約情報の取得",
        "description": "指定したContractIdのDPF契約を取得します。\n",
        "tags": [
          "contracts"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchContract",
        "summary": "DPF契約情報の更新",
        "description": "指定したContractIdのDPF契約を更新します。\n",
        "tags": [
          "contracts"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/labels": {
      "get": {
        "operationId": "getContractLabels",
        "summary": "DPF契約情報のラベル一覧取得",
        "description": "指定したContractIdのラベルの一覧を取得します。\n",
        "tags": [
          "contracts"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "put": {
        "operationId": "putContractLabels",
        "summary": "DPF契約情報のラベル一括更新",
        "description": "指定したContractIdのラベルを一括更新します。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "contracts"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/zones": {
      "get": {
        "operationId": "getContractsZoneList",
        "summary": "DPF契約に紐付くゾーンの一覧取得",
        "description": "指定したContractIdのDPF契約に紐付くゾーンの一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "zones (contracts)"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/zones/common_configs": {
      "patch": {
        "operationId": "patchContractsZoneCommonConfigs",
        "summary": "DPF契約に紐付くゾーンの共通設定の更新",
        "description": "指定したContractIdの共通設定を切り替えます。\n",
        "tags": [
          "zones (contracts)"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/zones/count": {
      "get": {
        "operationId": "getContractsZoneListCount",
        "summary": "DPF契約に紐付くゾーンの件数取得",
        "description": "指定したContractIdのDPF契約に紐付くゾーンの件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "zones (contracts)"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/lb_domains": {
      "get": {
        "operationId": "getContractsLbDomainList",
        "summary": "DPF契約に紐付くLBドメインの一覧取得",
        "description": "指定したContractIdのDPF契約に紐付くLBドメインの一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "lb_domains (contracts)"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/lb_domains/common_configs": {
      "patch": {
        "operationId": "patchContractsLbDomainCommonConfigs",
        "summary": "DPF契約に紐付くLBドメインの共通設定の更新",
        "description": "指定したContractIdの共通設定を切り替えます。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "lb_domains (contracts)"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/lb_domains/count": {
      "get": {
        "operationId": "getContractsLbDomainListCount",
        "summary": "DPF契約に紐付くLBドメインの件数取得",
        "description": "指定したContractIdのDPF契約に紐付くLBドメインの件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "lb_domains (contracts)"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/default_ttl": {
      "get": {
        "operationId": "getDefaultTtlList",
        "summary": "デフォルトTTLの取得",
        "description": "デフォルトTTLの一覧を取得します。\n",
        "tags": [
          "default_ttl"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchDefaultTtl",
        "summary": "デフォルトTTLの更新",
        "description": "デフォルトTTLを更新します。\\\n[**編集中レコードのゾーン反映**](#tag/zones/operation/patchZoneChanges)を実行するまでは権威サーバには反映されません。\n",
        "tags": [
          "default_ttl"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/default_ttl/changes": {
      "delete": {
        "operationId": "deleteDefaultTtlChanges",
        "summary": "編集中デフォルトTTLの取消",
        "description": "デフォルトTTLの操作を取消します。\n",
        "tags": [
          "default_ttl"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/default_ttl/diffs": {
      "get": {
        "operationId": "getDefaultTtlDiffs",
        "summary": "デフォルトTTLの編集差分の取得",
        "description": "現在DNSに登録されているデフォルトTTLと反映予定のデフォルトTTLの差分一覧を取得します。\n",
        "tags": [
          "default_ttl"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/delegations": {
      "get": {
        "operationId": "getDelegationList",
        "summary": "ネームサーバ申請候補の一覧取得",
        "description": "ネームサーバとして申請可能なゾーンの候補の一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "delegations"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postDelegation",
        "summary": "ネームサーバ申請",
        "description": "指定したゾーンを申請します。\n",
        "tags": [
          "delegations"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/delegations/count": {
      "get": {
        "operationId": "getDelegationListCount",
        "summary": "ネームサーバ申請候補の件数取得",
        "description": "ネームサーバとして申請可能なゾーンの候補の件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "delegations"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/dnssec": {
      "get": {
        "operationId": "getDnssecList",
        "summary": "DNSSEC情報の取得",
        "description": "DNSSEC情報の一覧を取得します。\n",
        "tags": [
          "dnssec"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchDnssec",
        "summary": "DNSSEC情報の更新",
        "description": "DNSSECの情報を更新します。\n",
        "tags": [
          "dnssec"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/dnssec/ksk_rollover": {
      "patch": {
        "operationId": "patchDnssecKskRollover",
        "summary": "KSKロールオーバーの開始",
        "description": "指定したゾーンに対してKSKロールオーバーを開始します。\\\nロールオーバーはds_stateが「3」の場合のみ開始できます。\n",
        "tags": [
          "dnssec"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/ds_records": {
      "get": {
        "operationId": "getDsRecordList",
        "summary": "DSレコードの一覧取得",
        "description": "上位のネームサーバに登録が必要なDSレコードを取得できます。\n",
        "tags": [
          "ds_records"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/jobs/{RequestId}": {
      "get": {
        "operationId": "getJob",
        "summary": "非同期リクエストの状態確認",
        "description": "ジョブの進捗状況を取得します。\\\nこのAPIの詳しい利用方法は、[**非同期リクエスト**](#section/2./2.4)を参照してください。\n",
        "tags": [
          "jobs"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/logs": {
      "get": {
        "operationId": "getContractsLogList",
        "summary": "DPF契約操作ログの一覧取得",
        "description": "DPF契約を操作したログの一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "logs (contracts)"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/logs/count": {
      "get": {
        "operationId": "getContractsLogListCount",
        "summary": "DPF契約操作ログの件数取得",
        "description": "DPF契約を操作したログの件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "logs (contracts)"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/logs": {
      "get": {
        "operationId": "getZonesLogList",
        "summary": "ゾーン操作ログの一覧取得",
        "description": "ゾーンを操作したログの一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "logs (zones)"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/logs/count": {
      "get": {
        "operationId": "getZonesLogListCount",
        "summary": "ゾーン操作ログの件数取得",
        "description": "ゾーンを操作したログの件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "logs (zones)"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/ping": {
      "get": {
        "x-iij-operationId": "getPing",
        "operationId": "getPing",
        "summary": "API疎通確認",
        "description": "APIへの疎通を確認できます。\n",
        "tags": [
          "ping"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          },
          {
            "DPFOperator": [
              "dpf_write"
            ]
          },
          {
            "ContractOperator": [
              "dpf_contract"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/qps/histories": {
      "get": {
        "operationId": "getQpList",
        "summary": "月別のQPSの一覧取得",
        "description": "DPF契約の月別のQPSを取得できます。\\\nDPF契約に紐付くゾーンおよびLBドメインの月別のQPSと、\\\nゾーンおよびLBドメインのクエリ数を元に集計したDPF契約の月別のQPSが取得できます。\n",
        "tags": [
          "qps"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/records": {
      "get": {
        "operationId": "getRecordList",
        "summary": "レコードの一覧取得",
        "description": "レコード情報の一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "put": {
        "operationId": "putRecord",
        "summary": "レコードの一括更新",
        "description": "レコードを一括更新します。\\\n[**編集中レコードのゾーン反映**](#tag/zones/operation/patchZoneChanges)を実行するまでは権威サーバには反映されません。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postRecord",
        "summary": "レコードの作成",
        "description": "新しくレコードを作成します。\\\n[**編集中レコードのゾーン反映**](#tag/zones/operation/patchZoneChanges)を実行するまでは権威サーバには反映されません。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/records/count": {
      "get": {
        "operationId": "getRecordListCount",
        "summary": "レコードの件数取得",
        "description": "レコード情報の件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/records/currents": {
      "get": {
        "operationId": "getRecordCurrents",
        "summary": "DNS反映済レコードの一覧取得",
        "description": "現在DNSに登録されているレコードの一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/records/currents/count": {
      "get": {
        "operationId": "getRecordCurrentsCount",
        "summary": "DNS反映済レコードの件数取得",
        "description": "現在DNSに登録されているレコードの件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/records/diffs": {
      "get": {
        "operationId": "getRecordDiffs",
        "summary": "レコードの編集差分の一覧取得",
        "description": "現在DNSに登録されているレコードと反映予定のレコードの差分一覧を取得します。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/records/diffs/count": {
      "get": {
        "operationId": "getRecordDiffsCount",
        "summary": "レコードの編集差分の件数取得",
        "description": "現在DNSに登録されているレコードと反映予定のレコードの差分数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/records/{RecordId}": {
      "get": {
        "operationId": "getRecord",
        "summary": "レコードの取得",
        "description": "指定したRecordIdのレコードを取得します。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchRecord",
        "summary": "レコードの更新",
        "description": "指定したRecordIdのレコードを更新します。\\\n[**編集中レコードのゾーン反映**](#tag/zones/operation/patchZoneChanges)を実行するまでは権威サーバには反映されません。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteRecord",
        "summary": "レコードの削除",
        "description": "指定したRecordIdのレコードを削除します。\\\n[**編集中レコードのゾーン反映**](#tag/zones/operation/patchZoneChanges)を実行するまでは権威サーバには反映されません。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/records/{RecordId}/changes": {
      "delete": {
        "operationId": "deleteRecordChanges",
        "summary": "編集中レコードの取消",
        "description": "指定したRecordIdのレコードの操作を取消します。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/records/{RecordId}/ds_records": {
      "get": {
        "operationId": "getDsRecordsFromCds",
        "summary": "CDS経由のDSレコードの取得",
        "description": "指定したRecordIdのレコードによって取り込まれるCDS経由のDSレコードを取得します。\n",
        "tags": [
          "records"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/tsigs": {
      "get": {
        "operationId": "getTsigList",
        "summary": "TSIG鍵の一覧取得",
        "description": "TSIG鍵情報の一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "tsigs"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postTsig",
        "summary": "TSIG鍵の作成",
        "description": "新しくTSIG鍵を作成します。\n",
        "tags": [
          "tsigs"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/tsigs/count": {
      "get": {
        "operationId": "getTsigListCount",
        "summary": "TSIG鍵の件数取得",
        "description": "TSIG鍵の件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "tsigs"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/tsigs/{TsigId}": {
      "get": {
        "operationId": "getTsig",
        "summary": "TSIG鍵の取得",
        "description": "指定したTsigIdのTSIG鍵を取得します。\n",
        "tags": [
          "tsigs"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchTsig",
        "summary": "TSIG鍵の更新",
        "description": "指定したTsigIdのTSIG鍵を更新します。\n",
        "tags": [
          "tsigs"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteTsig",
        "summary": "TSIG鍵の削除",
        "description": "指定したTsigIdのTSIG鍵を削除します。\n",
        "tags": [
          "tsigs"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/tsigs/{TsigId}/common_configs": {
      "get": {
        "operationId": "getTsigCommonConfigs",
        "summary": "TSIG鍵を利用している共通設定の一覧取得",
        "description": "指定したTSIG鍵を使用している共通設定の一覧を取得します。\n",
        "tags": [
          "tsigs"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/contracts/{ContractId}/tsigs/{TsigId}/common_configs/count": {
      "get": {
        "operationId": "getTsigCommonConfigsCount",
        "summary": "TSIG鍵を利用している共通設定の件数取得",
        "description": "指定したTSIG鍵を使用している共通設定の件数を取得します。\n",
        "tags": [
          "tsigs"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/zone_histories": {
      "get": {
        "operationId": "getZoneHistoryList",
        "summary": "ゾーン反映履歴の一覧取得",
        "description": "ゾーン反映の履歴の一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "zone_histories"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/zone_histories/count": {
      "get": {
        "operationId": "getZoneHistoryListCount",
        "summary": "ゾーン反映履歴の件数取得",
        "description": "ゾーン反映の履歴の件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "zone_histories"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/zone_histories/{ZoneHistoryId}/text": {
      "get": {
        "operationId": "getZoneHistoryText",
        "summary": "ゾーン反映時のRFC1035形式のテキストの取得",
        "description": "ゾーン反映の履歴をRFC1035形式のテキストファイルで取得します。\n",
        "tags": [
          "zone_histories"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/zone_proxy": {
      "get": {
        "operationId": "getZoneProxyList",
        "summary": "ゾーンプロキシ設定の取得",
        "description": "ゾーンプロキシの設定を取得します。\n",
        "tags": [
          "zone_proxy"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchZoneProxy",
        "summary": "ゾーンプロキシ設定の更新",
        "description": "ゾーンプロキシの設定を更新します。\n",
        "tags": [
          "zone_proxy"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/zone_proxy/health_check": {
      "get": {
        "operationId": "getZoneProxyHealthCheck",
        "summary": "プライマリネームサーバのヘルスチェック結果の取得",
        "description": "ゾーン転送のヘルスチェック結果の一覧を取得します。\n",
        "tags": [
          "zone_proxy"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones": {
      "get": {
        "operationId": "getZoneList",
        "summary": "ゾーンの一覧取得",
        "description": "DPF契約に紐付くゾーンの一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/count": {
      "get": {
        "operationId": "getZoneListCount",
        "summary": "ゾーンの件数取得",
        "description": "DPF契約に紐付くゾーンの件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}": {
      "get": {
        "operationId": "getZone",
        "summary": "ゾーンの取得",
        "description": "指定したZoneIdのゾーンを取得します。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchZone",
        "summary": "ゾーンの更新",
        "description": "指定したZoneIdのゾーンを更新します。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/labels": {
      "get": {
        "operationId": "getZoneLabels",
        "summary": "ゾーンのラベル一覧取得",
        "description": "指定したZoneIdのラベルの一覧を取得します。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "put": {
        "operationId": "putZoneLabels",
        "summary": "ゾーンのラベル一括更新",
        "description": "指定したZoneIdのラベルを一括更新します。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/changes": {
      "patch": {
        "operationId": "patchZoneChanges",
        "summary": "編集中レコードのゾーン反映",
        "description": "編集中のレコードの操作を反映します。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteZoneChanges",
        "summary": "編集中レコードの一括取消",
        "description": "編集中のレコードの操作を一括で取り消します。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/atomic_changes": {
      "patch": {
        "operationId": "patchZoneAtomicChanges",
        "summary": "レコードの一括更新とゾーン反映",
        "description": "レコードの一括更新とゾーンの反映をアトミックに処理します。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/contract": {
      "get": {
        "operationId": "getZoneContract",
        "summary": "ゾーンに紐付くDPF契約情報の取得",
        "description": "指定したZoneIdのゾーンに紐付くDPF契約情報を取得します。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/zones/{ZoneId}/managed_dns_servers": {
      "get": {
        "operationId": "getZoneManagedDnsServers",
        "summary": "マネージドDNSサーバの一覧取得",
        "description": "指定したZoneIdのマネージドDNSサーバの一覧を取得します。\n",
        "tags": [
          "zones"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/lb_domains": {
      "get": {
        "operationId": "getLbDomainList",
        "summary": "LBドメインの一覧取得",
        "description": "DPF契約に紐付くLBドメインの一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "lb_domains"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/lb_domains/count": {
      "get": {
        "operationId": "getLbDomainListCount",
        "summary": "LBドメインの件数取得",
        "description": "DPF契約に紐付くLBドメインの件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "lb_domains"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}": {
      "get": {
        "operationId": "getLbDomain",
        "summary": "LBドメインの取得",
        "description": "指定したLbDomainIdのLBドメインを取得します。\n",
        "tags": [
          "lb_domains"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchLbDomain",
        "summary": "LBドメインの更新",
        "description": "指定したLbDomainIdのLBドメインを更新します。\\\nRuleResourceNameを指定することで適用ルールの切り替えができます。\n",
        "tags": [
          "lb_domains"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/labels": {
      "get": {
        "operationId": "getLbDomainLabels",
        "summary": "LBドメインのラベル一覧取得",
        "description": "指定したLbDomainIdのラベルの一覧を取得します。\n",
        "tags": [
          "lb_domains"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "put": {
        "operationId": "putLbDomainLabels",
        "summary": "LBドメインのラベル一括更新",
        "description": "指定したLbDomainIdのラベルを一括更新します。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "lb_domains"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/contract": {
      "get": {
        "operationId": "getLbDomainContract",
        "summary": "LBドメインに紐付くDPF契約情報の取得",
        "description": "指定したLbDomainIdのLBドメインに紐付くDPF契約情報を取得します。\n",
        "tags": [
          "lb_domains"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/monitorings": {
      "get": {
        "operationId": "getMonitoringList",
        "summary": "監視の一覧取得",
        "description": "監視の一覧を取得します。\n",
        "tags": [
          "monitorings"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postMonitoring",
        "summary": "監視の作成",
        "description": "新しく監視を作成します。\\\n作成できる最大件数は50件です。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "monitorings"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/monitorings/{MonitoringResourceName}": {
      "get": {
        "operationId": "getMonitoring",
        "summary": "監視の取得",
        "description": "指定したMonitoringResourceNameの監視を取得します。\n",
        "tags": [
          "monitorings"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchMonitoring",
        "summary": "監視の更新",
        "description": "指定したMonitoringResourceNameの監視を更新します。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "monitorings"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteMonitoring",
        "summary": "監視の削除",
        "description": "指定したMonitoringResourceNameの監視を削除します。\n",
        "tags": [
          "monitorings"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/sites": {
      "get": {
        "operationId": "getSiteList",
        "summary": "サイトの一覧取得",
        "description": "サイトの一覧を取得します。\n",
        "tags": [
          "sites"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postSite",
        "summary": "サイトの作成",
        "description": "新しくサイトを作成します。\\\n作成できる最大件数は50件です。\n",
        "tags": [
          "sites"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/sites/{SiteResourceName}": {
      "get": {
        "operationId": "getSite",
        "summary": "サイトの取得",
        "description": "指定したSiteResourceNameのサイトを取得します。\n",
        "tags": [
          "sites"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchSite",
        "summary": "サイトの更新",
        "description": "指定したSiteResourceNameのサイトを更新します。\n",
        "tags": [
          "sites"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteSite",
        "summary": "サイトの削除",
        "description": "指定したSiteResourceNameのサイトを削除します。\n",
        "tags": [
          "sites"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/sites/{SiteResourceName}/endpoints": {
      "get": {
        "operationId": "getEndpointList",
        "summary": "エンドポイントの一覧取得",
        "description": "エンドポイントの一覧を取得します。\n",
        "tags": [
          "endpoints"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postEndpoint",
        "summary": "エンドポイントの作成",
        "description": "新しくエンドポイントを作成します。\\\n作成できる最大件数は50件です。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "endpoints"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/sites/{SiteResourceName}/endpoints/{EndpointResourceName}": {
      "get": {
        "operationId": "getEndpoint",
        "summary": "エンドポイントの取得",
        "description": "指定したEndpointResourceNameのエンドポイントを取得します。\n",
        "tags": [
          "endpoints"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchEndpoint",
        "summary": "エンドポイントの更新",
        "description": "指定したEndpointResourceNameのエンドポイントを更新します。\\\nエラー発生時はErrorDetailsにtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "endpoints"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteEndpoint",
        "summary": "エンドポイントの削除",
        "description": "指定したEndpointResourceNameのエンドポイントを削除します。\n",
        "tags": [
          "endpoints"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/sites/{SiteResourceName}/endpoints/{EndpointResourceName}/failover": {
      "post": {
        "operationId": "postEndpointFailover",
        "summary": "エンドポイントの手動切り離し",
        "description": "指定したEndpointResourceNameのエンドポイントの手動切り離しを実行します。\n",
        "tags": [
          "endpoints"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/sites/{SiteResourceName}/endpoints/{EndpointResourceName}/failback": {
      "post": {
        "operationId": "postEndpointFailback",
        "summary": "エンドポイントの手動切り戻し",
        "description": "指定したEndpointResourceNameのエンドポイントの手動切り戻しを実行します。\n",
        "tags": [
          "endpoints"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/rules": {
      "get": {
        "operationId": "getRuleList",
        "summary": "ルールの一覧取得",
        "description": "ルールの一覧を取得します。\n",
        "tags": [
          "rules"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postRule",
        "summary": "ルールの作成",
        "description": "新しくルールを作成します。\\\n作成できる最大件数は10件です。\n",
        "tags": [
          "rules"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/rules/{RuleResourceName}": {
      "get": {
        "operationId": "getRule",
        "summary": "ルールの取得",
        "description": "指定したRuleResourceNameのルールを取得します。\n",
        "tags": [
          "rules"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchRule",
        "summary": "ルールの更新",
        "description": "指定したRuleResourceNameのルールを更新します。\n",
        "tags": [
          "rules"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteRule",
        "summary": "ルールの削除",
        "description": "指定したRuleResourceNameのルールを削除します。\n",
        "tags": [
          "rules"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/rules/{RuleResourceName}/rule_methods": {
      "get": {
        "operationId": "getRuleMethodList",
        "summary": "ルールメソッドの一覧取得",
        "description": "ルールメソッドの一覧を取得します。\n",
        "tags": [
          "rule_methods"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "postRuleMethod",
        "summary": "ルールメソッドの作成",
        "description": "新しくルールメソッドを作成します。\\\n作成できるメソッドは最大6階層です。\n",
        "tags": [
          "rule_methods"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/rules/{RuleResourceName}/rule_methods/{RuleMethodResourceName}": {
      "get": {
        "operationId": "getRuleMethod",
        "summary": "ルールメソッドの取得",
        "description": "指定したRuleMethodResourceNameのルールメソッドを取得します。\n",
        "tags": [
          "rule_methods"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "patch": {
        "operationId": "patchRuleMethod",
        "summary": "ルールメソッドの更新",
        "description": "指定したRuleMethodResourceNameのルールメソッドを更新します。\n",
        "tags": [
          "rule_methods"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "deleteRuleMethod",
        "summary": "ルールメソッドの削除",
        "description": "指定したRuleMethodResourceNameのルールメソッドを削除します。\n",
        "tags": [
          "rule_methods"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/config": {
      "get": {
        "operationId": "getConfigList",
        "summary": "設定の一覧取得",
        "description": "設定の一覧を取得します。\n",
        "tags": [
          "config"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      },
      "put": {
        "operationId": "putConfig",
        "summary": "設定の一括更新",
        "description": "設定を一括更新します。\\\nエラー発生時はErrorDetailsにJSONPath形式のtargetキーが付与され、問題の箇所が特定できます。\n",
        "tags": [
          "config"
        ],
        "security": [
          {
            "DPFOperator": [
              "dpf_write"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/logs": {
      "get": {
        "operationId": "getLbDomainsLogList",
        "summary": "LBドメイン操作ログの一覧取得",
        "description": "LBドメインを操作したログの一覧を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "logs (lb_domains)"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    },
    "/lb_domains/{LbDomainId}/logs/count": {
      "get": {
        "operationId": "getLbDomainsLogListCount",
        "summary": "LBドメイン操作ログの件数取得",
        "description": "LBドメインを操作したログの件数を取得します。\\\n\"_keywords\" から始まるパラメータは、合計で30個まで指定可能です。\n",
        "tags": [
          "logs (lb_domains)"
        ],
        "security": [
          {
            "DPFViewer": [
              "dpf_read"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "DPFOperator": {
        "description": "IIJ-IDで[設定]の更新権限を持ったユーザが発行したアクセストークン",
        "type": "http",
        "scheme": "bearer"
      },
      "DPFViewer": {
        "description": "IIJ-IDで[設定]の参照権限を持ったユーザが発行したアクセストークン",
        "type": "http",
        "scheme": "bearer"
      },
      "ContractOperator": {
        "description": "IIJ-IDで[運用]の更新権限を持ったユーザが発行したアクセストークン",
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "tags": [
    {
      "name": "cc_primaries",
      "description": "プライマリネームサーバの操作ができます。\\\nプライマリネームサーバの状態（enabled）は以下のとおりです。\n\n### enabled\n値 | 意味 | 備考\n---|------|-----\n0 | 無効 |\n1 | 有効 |\n"
    },
    {
      "name": "cc_sec_notified_servers",
      "description": "DNS NOTIFYの操作ができます。\n"
    },
    {
      "name": "cc_sec_transfer_acls",
      "description": "ゾーン転送ACLの操作ができます。\n"
    },
    {
      "name": "cc_notice_accounts",
      "description": "通知先アカウントの操作ができます。\n"
    },
    {
      "name": "common_configs",
      "description": "複数のゾーンおよびLBドメインで共通の設定内容を使用するための共通設定を操作できます。\\\nマネージドDNSサーバの状態（managed_dns_enabled）、初期適用の共通設定（default）は以下のとおりです。\n\n### managed_dns_enabled\n値 | 意味 | 備考\n---|------|-----\n0 | 無効 |\n1 | 有効 |\n\n### default\n値 | 意味 | 備考\n---|------|-----\n0 | 無効 |\n1 | 有効 |\n"
    },
    {
      "name": "contracts",
      "description": "DPF契約の操作ができます。\\\n契約プラン（plan）、契約の状態（state）、お気に入りの状態（favorite）は以下のとおりです。\n\n### plan\n値 | 意味 | 備考\n---|------|-----\n 1 | ベーシック |\n 2 | プレミアム |\n\n### state\n値 | 意味 | 備考\n---|------|-----\n 1 | 利用開始前 |\n 2 | 利用中 |\n\n### favorite\n値 | 意味 | 備考\n---|------|-----\n 1 | 表示優先度高 |\n 2 | 表示優先度低 |\n"
    },
    {
      "name": "contract_partners",
      "description": "DPF契約の連携しているサービス情報の操作ができます。\n"
    },
    {
      "name": "logs (contracts)",
      "description": "DPF契約を操作したログを取得できます。\\\n取得可能なログは90日前までとなります。\\\n操作内容（operation）、ログの種別（log_type）、処理の状態（status）は以下のとおりです。\n\n### operation\n値 | 意味 | 備考\n---|------|-----\nadd_cc_primary | プライマリネームサーバ設定の作成 |\nupdate_cc_primary | プライマリネームサーバ設定の更新 |\ndelete_cc_primary | プライマリネームサーバ設定の削除 |\nadd_cc_sec_notified_server | DNS NOTIFY設定の作成 |\nupdate_cc_sec_notified_server | DNS NOTIFY設定の更新 |\ndelete_cc_sec_notified_server | DNS NOTIFY設定の削除 |\nadd_cc_sec_transfer_acl | ゾーン転送ACLの作成 |\nupdate_cc_sec_tra[...]"
    },
    {
      "name": "qps",
      "description": ""
    },
    {
      "name": "tsigs",
      "description": "TSIG鍵の操作ができます。\\\nハッシュアルゴリズム（algorithm）は以下のとおりです。\n\n### algorithm\n値 | 意味 | 備考\n---|------|-----\n0 | HMAC-SHA256 |\n"
    },
    {
      "name": "zones (contracts)",
      "description": "DPF契約に紐付くゾーンの操作ができます。\\\nゾーンの状態（state）、お気に入りの状態（favorite）、ゾーンプロキシの状態（zone_proxy_enabled）の詳細な説明は、[**zones**](#tag/zones)を参照してください。\n"
    },
    {
      "name": "lb_domains (contracts)",
      "description": "DPF契約に紐付くLBドメインの操作ができます。\\\nLBドメインの状態（state）、お気に入りの状態（favorite）の詳細な説明は、[**lb_domains**](#tag/lb_domains)を参照してください。\n"
    },
    {
      "name": "default_ttl",
      "description": "契約に紐づくゾーンのデフォルトTTLの操作ができます。\\\nデフォルトTTLの状態（state）は以下のとおりです。\n\n### state\n値 | 意味 | 備考\n---|------|-----\n 0 | 反映済み |\n 3 | 更新予定 |\n 5 | 更新前の状態 |\n"
    },
    {
      "name": "dnssec",
      "description": "DNSSECの操作ができます。\\\nDNSSECの有効状態（enabled）、DNSSECの状態（state）、DSレコードの状態（ds_state）は以下のとおりです。\n\n### enabled\n値 | 意味 | 備考\n---|------|-----\n0 | 無効 |\n1 | 有効 |\n\n### state\n値 | 意味 | 備考\n---|------|-----\n0 | ゾーン公開前 |\n1 | 有効化作業中 |\n2 | 有効 |\n3 | 無効化作業中 |\n4 | 無効 |\n\n### ds_state\n値 | 意味 | 備考\n---|------|-----\n0 | 公開前 |\n1 | DSレコード登録待ち   |\n3 | DSレコード公開中 |\n4 | ロールオーバー準備中 |\n5 | DSレコード変更待ち |\n6 | DSレコード変更反映待ち |\n7 | DSレコード削除待ち |\n8 | DSレコード削除反映待ち |\n"
    },
    {
      "name": "ds_records",
      "description": ""
    },
    {
      "name": "logs (zones)",
      "description": "契約に紐付くゾーンを操作したログを取得できます。\\\n取得可能なログは90日前までとなります。\\\n操作内容（operation）、ログの種別（log_type）、処理の状態（status）は以下のとおりです。\n\n### operation\n値 | 意味 | 備考\n---|------|-----\nupdating_default_ttl | デフォルトTTLの更新 |\ndismiss_default_ttl_change | 編集中デフォルトTTLの取消 |\nupdate_dnssec_configuration | DNSSEC情報の更新 |\nbegin_ksk_rollover | KSKロールオーバーの開始 |\nadding_record | レコードの作成 |\nupdating_record | レコードの更新 |\ndeleting_record | レコードの削除 |\ndismiss_record_change | 編集中レコードの取消 |\nupdate_zone_proxy | ゾーンプロキシ設定の[...]"
    },
    {
      "name": "records",
      "description": "契約に紐付くゾーンのレコード操作ができます。\\\nレコード操作の状態（state）は以下のとおりです。\n\n### state\n値 | 意味 | 備考\n---|------|-----\n 0 | 反映済み |\n 1 | 追加予定 |\n 2 | 削除予定 |\n 3 | 更新予定 |\n 5 | 更新前の状態 |\n"
    },
    {
      "name": "zone_histories",
      "description": "当日を含めて90日前までのゾーン反映の履歴を確認できます。\\\n確認のタイミングにより、それ以前の履歴を確認できる場合があります。\n"
    },
    {
      "name": "zone_proxy",
      "description": "ゾーンプロキシの操作ができます。\\\nゾーンプロキシの状態（enabled）、ゾーン転送の状態（state）は以下のとおりです。\n\n### enabled\n値 | 意味 | 備考\n---|------|-----\n 0 | 無効 |\n 1 | 有効 |\n\n### state\n値 | 意味 | 備考\n---|------|-----\n OK | ゾーン転送成功 |\n NG | ゾーン転送失敗 |\n"
    },
    {
      "name": "zones",
      "description": "DPF契約に紐付くゾーンの操作ができます。\\\nゾーンの状態（state）、お気に入りの状態（favorite）、ゾーンプロキシの状態（zone_proxy_enabled）は以下のとおりです。\n\n### state\n値 | 意味 | 備考\n---|------|-----\n 1 | 公開前 |\n 2 | 公開 |\n\n### favorite\n値 | 意味 | 備考\n---|------|-----\n 1 | 表示優先度高 |\n 2 | 表示優先度低 |\n\n### zone_proxy_enabled\n値 | 意味 | 備考\n---|------|-----\n 0 | 無効 |\n 1 | 有効 |\n"
    },
    {
      "name": "lb_domains",
      "description": "DPF契約に紐付くLBドメインの操作ができます。\\\nLBドメインの状態（state）、お気に入りの状態（favorite）は以下のとおりです。\n\n### state\n値 | 意味 | 備考\n---|------|-----\n 1 | 公開前 |\n 2 | 公開 |\n\n### favorite\n値 | 意味 | 備考\n---|------|-----\n 1 | 表示優先度高 |\n 2 | 表示優先度低 |\n"
    },
    {
      "name": "monitorings",
      "description": "LBドメインに紐付く監視の操作ができます。\n"
    },
    {
      "name": "sites",
      "description": "LBドメインに紐付くサイトの操作ができます。\n"
    },
    {
      "name": "endpoints",
      "description": "サイトに紐付くエンドポイントの操作ができます。\n"
    },
    {
      "name": "rules",
      "description": "LBドメインに紐付くルールの操作ができます。\\\n適用ルールは[**LBドメインの更新**](#tag/lb_domains/operation/patchLbDomain)で切り替えができます。\n"
    },
    {
      "name": "rule_methods",
      "description": "ルールに紐付くルールメソッドの操作ができます。\n"
    },
    {
      "name": "config",
      "description": "LBドメインに紐付く設定と状態の操作ができます。\n"
    },
    {
      "name": "logs (lb_domains)",
      "description": "契約に紐付くLBドメインを操作したログを取得できます。\\\n取得可能なログは90日前までとなります。\\\n操作内容（operation）、ログの種別（log_type）、処理の状態（status）は以下のとおりです。\n\n### operation\n値 | 意味 | 備考\n---|------|-----\nupdate_lb_domain_description | トラフィックコントロール契約のコメントの更新 |\nupdate_lb_domain_favorite | トラフィックコントロール契約のお気に入り状態の切り替え |\nupdate_lb_domain_labels | トラフィックコントロール契約のラベルの更新 |\nupdate_lb_domain_rule | 適用ルールの切り替え |\nadd_rule | ルールの追加 |\nupdate_rule | ルールの更新 |\ndelete_rule | ルールの削除 |\nadd_rule_method | ルールメソッドの追加 |\nupdate_rule_[...]"
    },
    {
      "name": "delegations",
      "description": "ネームサーバ申請の操作ができます。\\\nお気に入りの状態（favorite）、ネームサーバの状態（requested）は以下のとおりです。\n\n### favorite\n値 | 意味 | 備考\n---|------|-----\n1 | 表示優先度高 |\n2 | 表示優先度低 |\n\n### requested\n値 | 意味 | 備考\n---|------|-----\n0 | 未申請 |\n1 | 申請済み |\n"
    },
    {
      "name": "jobs",
      "description": "非同期リクエストの状態確認ができます。\\\nリクエストの状態（status）は以下のとおりです。\n\n### status\n値 | 意味 | 備考\n---|------|-----\nRUNNING | 処理中 |\nSUCCESSFUL | 正常終了 |\nFAILED | 異常終了 |\n"
    },
    {
      "name": "ping",
      "description": ""
    }
  ],
  "x-tagGroups": [
    {
      "name": "IIJ DNSプラットフォームサービス",
      "tags": [
        "cc_notice_accounts",
        "cc_primaries",
        "cc_sec_notified_servers",
        "cc_sec_transfer_acls",
        "common_configs",
        "contracts",
        "contract_partners",
        "lb_domains (contracts)",
        "logs (contracts)",
        "qps",
        "tsigs",
        "zones (contracts)"
      ]
    },
    {
      "name": "IIJマネージドDNSサービス",
      "tags": [
        "default_ttl",
        "dnssec",
        "ds_records",
        "logs (zones)",
        "records",
        "zone_histories",
        "zone_proxy",
        "zones"
      ]
    },
    {
      "name": "IIJ DNSトラフィックマネージメントサービス",
      "tags": [
        "config",
        "endpoints",
        "lb_domains",
        "logs (lb_domains)",
        "monitorings",
        "rule_methods",
        "rules",
        "sites"
      ]
    },
    {
      "name": "サービス共通",
      "tags": [
        "delegations",
        "jobs",
        "ping"
      ]
    }
  ]
}
